### ISSUE TITLE
Figures for the corrected finetuning version

### ISSUE THREAD

**Issue by mahnerak** [ucinlp/autoprompt#16]
I found the figure data is available at:
https://github.com/ucinlp/autoprompt/tree/emnlp2020-figures
However, it looks like the fine-tuning results for (at least) dataset_size experiments is not updated in the repository. Can you please update them so we can refer to your results?

**Comment by rloganiv** [comment]
Sorry, just saw this. The corrected finetuning results are now available (in the `*.stable.csv` files).

**Comment by mahnerak** [comment]
@rloganiv Thanks a lot!
