### ISSUE TITLE
Streamlit demo

### ISSUE THREAD

**Issue by sameersingh** [ucinlp/autoprompt#21]
Main TODOs left after PR #20 are:

- [x] confirm code is correct in terms of implementation
- [x] make it prettier (see other HF+ST demos, like https://huggingface.co/zero-shot/,  https://huggingface.co/rag/)
- [x] get caching working
- [x] good goal: refactor/copy autoprompt code without the task specific stuff, i.e. customized to this demo

**Comment by sameersingh** [comment]
Other ideas:
- upload CSV or in general, easier to submit lots of instances
- provide existing datasets and/or trigger
- allow triggers to be learned or written
- triggers as training proceeds? (optional)

_note:_ I'm concerned about feature creep, so we should do things that are easy.

**Comment by rloganiv** [comment]
@yasamanrazeghi7 has started work on this in PR #22.

**Comment by rloganiv** [comment]
Closed by #22.
