### ISSUE TITLE
NLI Templates

### ISSUE THREAD

**Issue by nelson-liu** [ucinlp/autoprompt#23]
Hi all,

Thanks for releasing this codebase, it looks really nice! I'm interested in running some NLI experiments, but I noticed that the templates are missing (`coming soon`) for NLI on both the `master` and the `dev` branches---do you happen to remember what the run command would be?

Thanks!

**Comment by yasamanrazeghi7** [comment]
Hi Nelson,
I updated the readme, hope that helps.
