### ISSUE TITLE
About accuracy

### ISSUE THREAD

**Issue by syddd1122334** [ucinlp/autoprompt#39]
I run the program according to the github, and the accuracy rate based on roberta-large can only reach 86%. How can I modify it to improve the accuracy rate?
Thank you!

**Comment by rloganiv** [comment]
Hi @syddd1122334,

The main things to experiment with are varying the label tokens in `--label-map`, the number of trigger tokens (i.e., `[T]`s) in `--template` and the number of candidates considered `--num-cand`.

Generally speaking we found that that dev accuracy can vary pretty heavily depending on these parameters, where it can get as low as 74% on SST-2 for RoBERTa large and as high as 91.2%. You may need to run quite a few experiments to find a good prompt (we searched over ~25 different settings to get the result in the paper).

If it helps, according to my experiment logs it looks like the best configuration was:
```
python -m autoprompt.create_trigger \
    --train data/glue_data/SST-2/train.tsv \
    --dev data/glue_data/SST-2/dev.tsv \
    --template '<s> {sentence} [T] [T] [T] [T] [T] [P] . </s>' \
    --label-map '{"0": ["Ġworse", "Ġincompetence", "ĠWorse"], "1": ["ĠCris", "Ġmarvelous", "Ġphilanthrop"]}' \
    --num-cand 100 \
    --accumulation-steps 30 \
    --bsz 24 \
    --eval-size 48 \
    --iters 150 \
    --model-name roberta-large  
```
which returned the trigger: `['Ġatmosphere', 'Ġalot', 'Ġdialogue', 'ĠClone', 'Ġtotally']`.

Best,

@rloganiv

**Comment by syddd1122334** [comment]
Thank you for your reply, I will try training again.
