### ISSUE TITLE
Query about the function "encode_label" in autoprompt/utils.py

### ISSUE THREAD

**Issue by XM-WANG** [ucinlp/autoprompt#46]
Hi,

I am trying to reproduce your experiment's result of the relation extraction (Table 5 in the paper).

However, I got an error that "Label "xxx" gets mapped to multiple tokens." which is alerted by the function `encode_label` in the file `autopromot/utils.py`.

The command I used is:

```
python -m autoprompt.create_trigger \
    --train  {train_path} \
    --dev {dev_path} \
    --template '<s> {context} {sub_label} [T] [T] [T] [T] [T] [P] . </s>' \
    --num-cand 10 \
    --accumulation-steps 1 \
    --model-name roberta-large \
    --bsz 32 \
    --eval-size 32 \
    --iters 500 \
    --label-field 'obj_label' \
    --filter \
    --print-lama \
    --use-ctx \
    --perturbed \
    --tokenize-labels \
```

I noticed that the exception is customized by you. Could you please help me to check what's wrong with my command?

**Comment by taylorshin** [comment]
Only single token objects are considered for the label/prediction target. That error must mean that somehow one of the relation object labels is being split into multiple tokens. Do you mind sharing more details of your error so that we can pinpoint which label is causing it?

**Comment by XM-WANG** [comment]
Many thanks for your reply!

Here I list some labels that will cause this error. 
- (P17): ValueError: Label "Romania" gets mapped to multiple tokens.
- (P19): ValueError: Label "Constantinople" gets mapped to multiple tokens. 
- (P20): ValueError: Label "Edinburgh" gets mapped to multiple tokens.
- (P27): ValueError: Label "Iceland" gets mapped to multiple tokens.

I wrote a script to automatically run the experiment with different relations. Nealy all relations contain some labels that trigger this error. I doubt that it is because of some wrong arguments I used.

This problem happened when I added the argument "--perturbed" for the relation extraction experiments with RoBERTa.

Could you please provide your command for the perturbed relation extraction experiments with RoBERTa?

**Comment by taylorshin** [comment]
For experiments with RoBERTa, we only used examples where the label is a single token for both BERT and RoBERTa. I added code that handles the aforementioned ValueError so if you pull the latest code from the master branch you should be able to create triggers for perturbed relation extraction (with RoBERTa) without any errors.

**Comment by XM-WANG** [comment]
Many thanks for your help!
