### ISSUE TITLE
Is there the code for downstream task in this project？

### ISSUE THREAD

**Issue by Claymore715** [ucinlp/autoprompt#47]
to compare the efficiency between manual prompt and autoprompt

**Comment by taylorshin** [comment]
For evaluation of prompts for fact retrieval and relation extraction, refer to [this](https://github.com/ucinlp/autoprompt#evaluation-for-fact-retrieval-and-relation-extraction) section of the README. For the other tasks, you'll have to write some code that will load the eval dataset (SST-2 or SICK-E), append the trigger tokens, feed the full prompt into the LM, and score the results.
