### ISSUE TITLE
What is the T in your label search algorithm?

### ISSUE THREAD

**Issue by MM-IR** [ucinlp/autoprompt#55]
I am just very curious about your T tokens here - trigger placeholders (a new added special token in the tokenizer with random initialization?)! In other words, can you give me some explanations to your label set searching algorithm? Thanks in advance for your kind help!

**Comment by taylorshin** [comment]
The trigger tokens (i.e. [T]) are initialized to [MASK] tokens, not random tokens, that are added to the tokenizer as special tokens. In terms of your question, are you asking how the trigger tokens are connected to the automatic label token selection process for NLP tasks like sentiment analysis?

**Comment by MM-IR** [comment]
Yes, it sounds like in your label token selection process, you just simply add these trigger tokens as other <MASK> tokens, in tandem with the target MASK token, right? Interesting, thanks a lot for your patient explanations!
